### ISSUE TITLE
Get Text input fields to not take up the whole page

### ISSUE THREAD

**Issue by jesmith0** [code-for-tb/PITCensus#20]

**Comment by jamesrwaugh** [comment]
@andrewtelnov commented on methods to solve this here 
https://github.com/andrewtelnov/surveyjs/issues/71

**Comment by ZakMiller** [comment]
This leads to a weird effect where the dropdown on the page is a different width than the dropdown when you click it.
<img width="1134" alt="screen shot 2016-10-16 at 12 27 51 pm" src="https://cloud.githubusercontent.com/assets/18072671/19418927/03a77df6-939c-11e6-9752-8ae5a5dd5422.png">

**Comment by ZakMiller** [comment]
Gonna leave it as is
